// This file was auto-generated by Fern from our API Definition.

package api

import (
	time "time"
)

type GetTasksRouteRequest struct {
	// Whether to return base64 encoded URLs. If false, the URLs will be returned as presigned URLs.
	Base64Urls *bool `json:"-"`
	// End date
	End *time.Time `json:"-"`
	// Whether to include chunks in the output response
	IncludeChunks *bool `json:"-"`
	// Number of tasks per page
	Limit *int64 `json:"-"`
	// Page number
	Page *int64 `json:"-"`
	// Start date
	Start *time.Time `json:"-"`
}
