// Code generated by Fern. DO NOT EDIT.

package chunkrai

import (
	json "encoding/json"
	core "github.com/gitslim/chunkr-ai-sdk/sdk/go/chunkrai/core"
)

// Internal server error related to creating the task
type InternalServerError struct {
	*core.APIError
	Body string
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body string
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}
