// Code generated by Fern. DO NOT EDIT.

package chunkrai

import (
	time "time"
)

type GetTasksRouteRequest struct {
	// Whether to return base64 encoded URLs. If false, the URLs will be returned as presigned URLs.
	Base64Urls *bool `json:"-" url:"base64_urls,omitempty"`
	// End date
	End *time.Time `json:"-" url:"end,omitempty"`
	// Whether to include chunks in the output response
	IncludeChunks *bool `json:"-" url:"include_chunks,omitempty"`
	// Number of tasks per page
	Limit *int64 `json:"-" url:"limit,omitempty"`
	// Page number
	Page *int64 `json:"-" url:"page,omitempty"`
	// Start date
	Start *time.Time `json:"-" url:"start,omitempty"`
}
