// This file was auto-generated by Fern from our API Definition.

package task

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	sdkgo "github.com/gitslim/chunkr-ai-sdk/sdk/go"
	core "github.com/gitslim/chunkr-ai-sdk/sdk/go/core"
	option "github.com/gitslim/chunkr-ai-sdk/sdk/go/option"
	io "io"
	http "net/http"
	url "net/url"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Queues a document for processing and returns a TaskResponse containing:
// - Task ID for status polling
// - Initial configuration
// - File metadata
// - Processing status
// - Creation timestamp
// - Presigned URLs for file access
//
// The returned task will typically be in a `Starting` or `Processing` state.
// Use the `GET /task/{task_id}` endpoint to poll for completion.
func (c *Client) CreateTaskRoute(
	ctx context.Context,
	request *sdkgo.CreateForm,
	opts ...option.RequestOption,
) (*sdkgo.TaskResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.chunkr.ai"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "api/v1/task/parse"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 500:
			value := new(sdkgo.InternalServerError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response *sdkgo.TaskResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodPost,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Request:      request,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Retrieves detailed information about a task by its ID, including:
// - Processing status
// - Task configuration
// - Output data (if processing is complete)
// - File metadata (name, page count)
// - Timestamps (created, started, finished)
// - Presigned URLs for accessing files
//
// This endpoint can be used to:
// 1. Poll the task status during processing
// 2. Retrieve the final output once processing is complete
// 3. Access task metadata and configuration
func (c *Client) GetTaskRoute(
	ctx context.Context,
	// Id of the task to retrieve
	taskId *string,
	request *sdkgo.GetTaskRouteRequest,
	opts ...option.RequestOption,
) (*sdkgo.TaskResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.chunkr.ai"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"api/v1/task/%v", taskId)

	queryParams := make(url.Values)
	if request.Base64Urls != nil {
		queryParams.Add("base64_urls", fmt.Sprintf("%v", *request.Base64Urls))
	}
	if request.IncludeChunks != nil {
		queryParams.Add("include_chunks", fmt.Sprintf("%v", *request.IncludeChunks))
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 500:
			value := new(sdkgo.InternalServerError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response *sdkgo.TaskResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodGet,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Delete a task by its ID.
//
// Requirements:
// - Task must have status `Succeeded` or `Failed`
func (c *Client) DeleteTaskRoute(
	ctx context.Context,
	// Id of the task to delete
	taskId *string,
	opts ...option.RequestOption,
) error {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.chunkr.ai"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"api/v1/task/%v", taskId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 500:
			value := new(sdkgo.InternalServerError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodDelete,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return err
	}
	return nil
}

// Cancel a task that hasn't started processing yet:
// - For new tasks: Status will be updated to `Cancelled`
// - For updating tasks: Task will revert to the previous state
//
// Requirements:
// - Task must have status `Starting`
func (c *Client) CancelTaskRoute(
	ctx context.Context,
	// Id of the task to cancel
	taskId *string,
	opts ...option.RequestOption,
) error {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.chunkr.ai"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"api/v1/task/%v/cancel", taskId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 500:
			value := new(sdkgo.InternalServerError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodGet,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return err
	}
	return nil
}

// Updates an existing task's configuration and reprocesses the document.
// The original configuration will be used for all values that are not provided in the update.
//
// Requirements:
// - Task must have status `Succeeded` or `Failed`
// - New configuration must be different from the current one
//
// The returned task will typically be in a `Starting` or `Processing` state.
// Use the `GET /task/{task_id}` endpoint to poll for completion.
func (c *Client) UpdateTaskRoute(
	ctx context.Context,
	taskId string,
	request *sdkgo.UpdateForm,
	opts ...option.RequestOption,
) (*sdkgo.TaskResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.chunkr.ai"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"api/v1/task/%v/parse", taskId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 500:
			value := new(sdkgo.InternalServerError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return apiError
			}
			return value
		}
		return apiError
	}

	var response *sdkgo.TaskResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:          endpointURL,
			Method:       http.MethodPatch,
			MaxAttempts:  options.MaxAttempts,
			Headers:      headers,
			Client:       options.HTTPClient,
			Request:      request,
			Response:     &response,
			ErrorDecoder: errorDecoder,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
