// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/gitslim/chunkr-ai-sdk/sdk/go/core"
	health "github.com/gitslim/chunkr-ai-sdk/sdk/go/health"
	option "github.com/gitslim/chunkr-ai-sdk/sdk/go/option"
	task "github.com/gitslim/chunkr-ai-sdk/sdk/go/task"
	tasks "github.com/gitslim/chunkr-ai-sdk/sdk/go/tasks"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Task   *task.Client
	Tasks  *tasks.Client
	Health *health.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
		Task:   task.NewClient(opts...),
		Tasks:  tasks.NewClient(opts...),
		Health: health.NewClient(opts...),
	}
}
